### PR TITLE
stack.yaml, export data constructors

### PR DESCRIPTION
**Pull request by bitemyapp**
Needed this for database stuff where we know that if it got inserted, it was already validated. Can't make the types fit otherwise without introduce Identity/Maybe wrappers on the field and that's blehhhhhhhhh.

### CODE REVIEW

**Comment by Porges** [comment]
So, been thinking about this before when the stuff about `.Internals` came up on /r/haskell - but the whole point of the `EmailAddress` type is to prevent invalid addresses being constructed. Perhaps an `unsafeEmailAddress` would make more sense?

**Comment by bitemyapp** [comment]
@Porges `unsafeEmailAddress` would suit me right down to the ground :+1: :smile:

**Comment by Porges** [comment]
@bitemyapp One annoying thing: because `EmailAddress` stores local-part and domain separately, either `unsafeEmailAddress` has to have type `BS -> BS -> EmailAddress`, or it's going to have to do some minimal parsing anyway to split on the `@`. I'd prefer the former, but that doesn't really help if you're reading validated email addresses out of a database... 

Any preference? :)

**Comment by bitemyapp** [comment]
@Porges that occurred to me and was bothering me.

`BS -> BS -> EmailAddress` is fine, the standard doesn't allow for a `@` anywhere else, so a dumb split can be tolerated I think.

**Comment by Porges** [comment]
@bitemyapp will get this done after work hours today

**Comment by bitemyapp** [comment]
@Porges cheers :)

**Comment by bitemyapp** [comment]
@Porges <3

**Comment by Porges** [comment]
Shipped as v2.2.0.

**Pull request merged**
