### PR TITLE
Fix read instance and read test

### PR DESCRIPTION
**Pull request by L8D**
They were broken and it was driving me crazy

### CODE REVIEW

**Comment by L8D** [comment]
moving the `endOfInput` restraint from `addrSpec` to `validate` allows for an even more correct `Read` instance and more versatile usage.

**Comment by Porges** [comment]
Thanks for this! I'll test and look to publish a new version soon.

**Comment by Porges** [comment]
This should really be a major version bump since it changes the behaviour of `addrSpec`. On the other hand, it fixes a bug and `addrSpec` should really not have had `endOfInput` in it (in fact, it didn't use to back in v0.x). After searching around I can't find any uses of `addrSpec` outside this package (apart from yours), so I'm going to treat this as a minor version bump to 2.1...

**Comment by L8D** [comment]
yay!

**Comment by Porges** [comment]
Actually the read instance changes need some rethinking...

**Comment by L8D** [comment]
How so? I believe I copied code from an example in the AttoParsec docs, I
don't see what is wrong.

**Comment by Porges** [comment]
See discussion on #6.

For compatibility with this it needs to continue to read quoted strings.

**Comment by Porges** [comment]
Fixed it up, will re-do the release.

**Comment by Porges** [comment]
Or was reading quoted strings exactly what you meant by "broken"? :)

**Comment by L8D** [comment]
Before it was only reading quoted strings, which forced me to wrap it in a
newtype and write my own instance so I could use it for other purposes. I
would prefer it if your new implementation only optionally parses the
quotes.

**Comment by Porges** [comment]
Okay, I misinterpreted what your original issue was then - I thought it was mostly about `addrSpec` forcing EOF to occur. Sorry about the confusion... 

The `Read` instance for `EmailAddress` is really only so you can `read` back things that have been `show`n. If you want to go from a string directly to an email address you should use the `emailAddress` smart constructor.

Does that make sense? Could you share a bit more about how you want to use it?

**Pull request merged**
